
Respected Mam,
The inttofactconverter.py is the main file which I was working on this morning.
It is a program which converts integer values which are given by the user to a factorial form.

For eg,

4 Factorial (4!) means 1x2x3x4 

4! = 24

It also tells that if the input number is not in the factorial series, it will say that the given number cannot be converted to factorial and it also displays the nearest number in the series wrt the input number.
For eg,
5! = 120
If the input number is 121,
the program will say that

"Conversion Error!
Check to given Number properly
The member of factorial series that is nearby to the given number is 120
which is 5!"
***

This program was working fine until the last period. I think I have coded a keyword (most probably break) in the wrong place.

There is another file called test.py
It contains the code which i tried to debug
But it still has some errors

If possible can you debug my inttofacconverter.py file mam?

**You can certainly remove the function calling part mam**

**I think that the improper fuction calling might be the bug**
***
*Thanking You,*

A*kash Shanmugaraj*